name: Criptera
description: Cryptocurrency portfolio and market explorer.

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.18
  path_provider: ^2.0.13
  url_launcher: ^6.1.10
  http: ^0.13.5
  package_info: ^2.0.2
  awesome_circular_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
